=== SabrinaWSY/projet_XML_exos/Exos2/bibliographie2.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT bibliographie (#PCDATA | livre | article)*>
<!-- Livre -->
<!ELEMENT livre (#PCDATA | titre | auteur | tome | edition)*>
<!ATTLIST livre num CDATA #IMPLIED>
<!ELEMENT titre (#PCDATA)>
<!ATTLIST titre soustitre CDATA #IMPLIED >
<!ELEMENT auteur (#PCDATA)>
<!ATTLIST auteur num CDATA #IMPLIED>
<!ELEMENT tome EMPTY >
<!ATTLIST tome nb_pages CDATA #REQUIRED>
<!ATTLIST tome soustitre CDATA #IMPLIED >
<!ATTLIST tome num CDATA #IMPLIED>
<!ELEMENT lieu_ed (#PCDATA)>
<!ELEMENT edition (#PCDATA | maison | lieu_ed | lieu_imprim | ISBN)*>
<!ELEMENT lieu_imprim (#PCDATA)>
<!ELEMENT maison (#PCDATA)>
<!ELEMENT ISBN (#PCDATA)>
<!-- Article -->
<!ELEMENT article (titre | auteur | ref_publication | avis_perso)*>
<!ELEMENT journal (#PCDATA) >
<!ATTLIST journal nom_journal CDATA "Feuille de chou">
<!ATTLIST journal annee_publi ( 2000 | 2001 | 2002 | avant_2000 | inconnue) "inconnue">
<!ELEMENT ref_publication (#PCDATA | journal | numero_page | annee_pub | num_journal)*>
<!ELEMENT num_journal (#PCDATA)>
<!ELEMENT avis_perso (#PCDATA)>
<!ELEMENT numero_page (#PCDATA)>

=== SabrinaWSY/projet_XML_exos/Exos2/bibliographie2.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE bibliographie SYSTEM "file:/Users/siyuwang/Documents/TAL_M1/S2/XML/Site_Final/Exos2/bibliographie2.dtd">
<!-- Exos2 phase 2 Lara et Siyu-->
<bibliographie>
    <livre num="1">
        <titre>Harry Potter à l'école des sorciers</titre>
        <auteur>J.K.Rowling</auteur>
        <tome nb_pages="320"/>
        <edition>
            <maison>Gallimard jeunesse</maison>
            <lieu_ed>5 Rue Gaston Gallimard, 75007 Paris</lieu_ed>
            <lieu_imprim>Paris</lieu_imprim>
            <ISBN>2070584623</ISBN>
        </edition>
    </livre>
    <livre num="2">
        <titre>Hunger Games</titre>
        <auteur>Suzanne Collins</auteur>
        <tome soustitre="La révolte" nb_pages="646"/>
        <edition>
            <maison>Pocket Jeunesse</maison>
            <lieu_ed>Paris</lieu_ed>
            <lieu_imprim>Paris</lieu_imprim>
            <ISBN>2266260790</ISBN>
        </edition>
    </livre>
    <article>
        <titre>Automatic identification of word translations from unrelated English and German corpora.</titre>
        <auteur num="1">Reinhard Rapp</auteur>
        <ref_publication>
            <journal nom_journal="ACL" annee_publi="avant_2000"/>
            <numero_page>519–526</numero_page>
            <num_journal>37</num_journal>
        </ref_publication>
        <avis_perso>bien</avis_perso>
    </article>
</bibliographie>
