=== SabrinaWSY/projet_XML_exos/Exos2/bibliographie.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT bibliographie (#PCDATA | livre | article)*>
<!-- Livre -->
<!ELEMENT livre (#PCDATA | titre | auteur | tome | edition)*>
<!ATTLIST livre num CDATA #IMPLIED>
<!ELEMENT titre (#PCDATA)>
<!ELEMENT auteur (#PCDATA)>
<!ATTLIST auteur num CDATA #IMPLIED>
<!ELEMENT tome (#PCDATA | nb_page)*>
<!ATTLIST tome num CDATA #IMPLIED>
<!ELEMENT nb_page (#PCDATA)>
<!ELEMENT lieu_ed (#PCDATA)>
<!ELEMENT lieu_imprim (#PCDATA)>
<!ELEMENT edition (#PCDATA | maison | lieu_ed | lieu_imprim | ISBN)*>
<!ELEMENT ISBN (#PCDATA)>
<!ELEMENT maison (#PCDATA)>
<!-- Article -->
<!ELEMENT article (#PCDATA | titre | auteur | ref_publication | avis_perso)*>
<!ELEMENT annee_pub (#PCDATA)>
<!ELEMENT nom_journal (#PCDATA)>
<!ELEMENT ref_publication (#PCDATA | nom_journal | numero_page | annee_pub | num_journal)*>
<!ELEMENT num_journal (#PCDATA)>
<!ELEMENT numero_page (#PCDATA)>
<!ELEMENT avis_perso (#PCDATA)>

=== SabrinaWSY/projet_XML_exos/Exos2/bibliographie.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE bibliographie SYSTEM "file:/Users/siyuwang/Documents/TAL_M1/S2/XML/Site_Final/Exos2/bibliographie.dtd">
<!-- Exos2 phase 1 Lara et Siyu-->
<bibliographie>
    <livre num="1">
        <titre>Harry Potter à l'école des sorciers</titre>
        <auteur>J.K.Rowling</auteur>
        <tome num="1">
            <nb_page>320</nb_page>
        </tome>
        <edition>
            <maison>Gallimard jeunesse</maison>
            <lieu_ed>5 Rue Gaston Gallimard, 75007 Paris</lieu_ed>
            <lieu_imprim>Paris</lieu_imprim>
            <ISBN>2070584623</ISBN>
        </edition>
    </livre>
    <livre num="2">
        <titre>Hunger Games: La révolte</titre>
        <auteur>Suzanne Collins</auteur>
        <tome num="3">
            <nb_page>464</nb_page>
        </tome>
        <edition>
            <maison>Pocket Jeunesse</maison>
            <lieu_ed>Paris</lieu_ed>
            <lieu_imprim>Paris</lieu_imprim>
            <ISBN>2266260790</ISBN>
        </edition>
    </livre>
    <article>
        <titre>Automatic identification of word translations from unrelated English and German corpora.</titre>
        <auteur num="1">Reinhard Rapp</auteur>
        <ref_publication>
            <nom_journal>ACL</nom_journal>
            <numero_page>519–526</numero_page>
            <annee_pub>1999</annee_pub>
            <num_journal>37</num_journal>
        </ref_publication>
        <avis_perso>bien</avis_perso>
    </article>
</bibliographie>
